services:
  mysql:
    image: mysql:latest
    container_name: django-mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: seekers
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"